language: go
go:
  - 1.1

before_install:
  - export PROJECT="$PWD"
  - cd && git clone git://github.com/zeromq/libzmq.git && cd libzmq && ./autogen.sh && ./configure && make && sudo make install 

install:
  - cd "$PROJECT" && go get -tags zmq_3_x -d -v

script:
  - go test -ldflags='-r /usr/local/lib' -tags zmq_3_x -v
